version: '3.8'

services:
  db:
    image: postgres:12.2-alpine
    container_name: 'comments-database'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgres/data

  api:
    build: .
    container_name: 'comments-rest-api'
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres

    networks:
      - fullstack

    ports:
      - '8080:8080'
    depends_on:
      - db

networks:
  fullstack:
    driver: bridge

volumes:
  database_postgres:
