version: '3.8'

services:
  db:
    image: postgres:12.2-alpine
    container_name: 'comments-database'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      

    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgres/data

  api:
    build: .
    container_name: 'comments-rest-api'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST="db"
      - DB_PORT="5432"
      - DB_TABLE=postgres

    ports:
      - '8080:8080'
    depends_on:
      - db

networks:
  fullstack:
    driver: bridge

volumes:
  database_postgres:
